# Generated by Django 5.0.2 on 2024-05-08 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0003_article_article_image_article_author_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
