# Generated by Django 5.0.2 on 2024-05-08 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchstore', '0004_alter_product_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Owner',
            new_name='owner',
        ),
    ]
