# Generated by Django 5.0.2 on 2024-05-08 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='job',
            name='entry',
        ),
        migrations.RemoveField(
            model_name='job',
            name='updated_on',
        ),
    ]
