# Generated by Django 5.0.2 on 2024-05-08 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0002_remove_job_created_on_remove_job_entry_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commission',
            options={'ordering': ['created_on']},
        ),
    ]
